### ISSUE TITLE
Linker error: `cannot find -lSDL2d`

### ISSUE THREAD

**Issue by adomasbaliuka** [iris-engine-dev/asm_c_cpp#2]
(On Ubuntu)

The C++ and C programs seem to want to link to `SDL2d` but no such target gets built for me. What gets built is `libSDL2.a`, which I'm able to link to after renaming `SDL2d` -> `SDL2` inside both `target_link_libraries` CMake commands. This probably isn't intended though, is it? What am I doing wrong?

I'm also not sure if the game built this way works as intended, because it seems to be missing a lot of features (no win condition, no way to close the game window, no way to lose the game, etc...). The demo on Youtube doesn't show how complete this game is supposed to be. If this is as intended, you might want to at least mention in the README that it's not feature complete, lest people wonder what they're doing wrong.

**Comment by nathan-baggs** [comment]
You are right this is a "bare bones" game, with little in the way of actual game. That extends to the build system as well, which is by no means perfect. I suspect there is some shenanigans around using WSL, rather than on a real Linux box, which has caused inconsistent postfixing of built libraries.

A quick and dirty fix is as you mentioned: change `SDL2d` to `SDL2`. You are do nothing wrong, rather I am (:
